ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ com.animalartstudio.server.ApplicationKt.module ]
  }
}

animalArtStudio {
  database {
    url = "jdbc:h2:file:./data/animal-art-studio;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE"
    url = ${?DATABASE_URL}
    user = "sa"
    user = ${?DATABASE_USER}
    password = ""
    password = ${?DATABASE_PASSWORD}
  }
  coaching {
    nudgesRequiredForMagic = 5
  }
}
